### ISSUE TITLE
spec: MutableList streamtype

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/ceramic#104]

**Comment by oed** [comment]
@stbrody would you mind making the notion page public and sharing this in the CIP repo as a pre-draft CIP? I think our community would appreciate that!

**Comment by stbrody** [comment]
Done @oed 
PR: https://github.com/ceramicnetwork/CIP/pull/114
Issue: https://github.com/ceramicnetwork/CIP/issues/113
