### ISSUE TITLE
[WIP] Build an explorer for browsing Ceramic documents

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/ceramic#12]
*This issue is a work in progress. Please feel free to add recommendations or thoughts in the comments. As the explorer specification becomes more solidified, this document is subject to change.*

It would be awesome for someone in the community to create an explorer so developers/prosumers can easily discover documents on the Ceramic network via an interface.

#### UI Requirements
- Search documents (by docId, schema, user, contents?, ...)
- View search results
- Display popular/featured documents (i.e. profile schema tile, anchor service policy, ...)
- Display all network activity
- View a document:
  - Current state
  - Full history (update log)
  - 

#### Functional Requirements
- View documents
- Display the state of a record/update:
  - `Pending` (Signed record)
  - `Processing/Anchoring` (Submitted to a blockchain) [maybe this isn't needed?]
  - `Confirmed` (Anchor record added)
- 

#### Frontend Technology
React

#### Backend Technology
The explorer would be most performant and feature-complete if it was built on an index, but for the MVP we could likely directly query the network.
- Configurable max cache for webUI for loading documents it sees

cc @oed @kamescg @msterle @pedrouid @simonovic86 

### Home Page
![ceramic_explorer_concept](https://user-images.githubusercontent.com/5216274/80047140-a12c6680-84da-11ea-9353-bb4d545f8a6d.png)

# What is the MVP
## Requirements
- Lookup document by docId
- NFT doc for features documents
- Recently updated
  - Document Id

**Comment by yanivtal** [comment]
Is it okay if the documents only show up in the explorer after they've been snapshotted onchain? If so we can index and serve GraphQL for the client on The Graph.

We've been working with Gatsby and Theme UI to great effect. We're open sourcing an app next week that could be a great starting point. Fulltext search, grid and list views with sorting and filtering.

**Comment by michaelsena** [comment]
Definitely okay if docs only show up after they've been anchored. However, I think it could be useful to also display docs that have been submitted to the network, but that are pending anchoring. This would have some sort of pending tag on the doc update. We might be able to gather that info directly from Ceramic nodes though and use The Graph for everything else.

The template app sounds awesome @yanivtal, and something we would likely use for the explorer! Feel free to share the repo whenever it's available. 

@oed @kamescg

**Comment by yanivtal** [comment]
That makes sense. The explorer could show in progress updates from the p2p network + documents that have been anchored. This is similar to not having a change confirmed in a chain.

We're open sourcing in the next few days :)

**Comment by kamescg** [comment]
@michaelsena Is there a repo started for the above design concept?

**Comment by michaelsena** [comment]
@kamescg not yet, we're still finalizing the spec and defining the MVP - but when it's done I can let you know. 👍

**Comment by kamescg** [comment]
coolio - let me know if you want help setting up the initial application.
