### ISSUE TITLE
Implementing hello world libp2p protocol via plugin system

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/ceramic#138]
A basic libp2p protocol that does something simple, but deepens our understanding of how custom libp2p protocols work and are written, and specifically aims to answer the questions below.

- [ ] Does the existing plugin systems for libp2p/ipfs expose everything we need to implement TipSync, or are there missing features?
- [ ] How will a Ceramic node providing a stream provide the tip to libp2p?  The custom libp2p protocol will allow the extended go-ipfs node backing a ceramic instance to receive a request via libp2p for the tip of a given stream, but the ipfs/libp2p node needs a way to know the current tip from the Ceramic node that is using it.
    - Ceramic node could tell ipfs every time the tip is updated, but then ipfs is maintaining a map of streamid to tips that duplicates information the ceramic node already stores in the state store
    - Ceramic could long-poll ipfs, similar to how pubsub works today, and get a message for incoming TipExchange request.  After getting such a request, it could call an HTTP endpoint on the IPFS node to inform it of the tip for the given streamid.

**Comment by stbrody** [comment]
closing in favor of https://github.com/ceramicnetwork/ceramic/issues/172 now that we are no longer planning on building this into go-libp2p
