### ISSUE TITLE
Plugin distribution plan

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/ceramic#141]
Now that we have a repo with a simple ipfs/libp2p plugin, we need a plan for once the full TipSync implementation is complete, how do we make a version of go-ipfs with TipSync support available to our users?

- [ ] How will we distribute the plugin?  Do we have to build a new go-ipfs binary with our extensions added in for every platform we want to support and distribute that binary ourselves?  Or can we distribute the source somewhere and have our users build the go-ipfs binary with TipSync support themselves?
- [ ] Can we get PL to add TipSync support to upstream go-ipfs?  Probably not, but worth a try.

**Comment by stbrody** [comment]
We no longer plan to use a go-ipfs plugin for tipsync
