### ISSUE TITLE
Spec: Release process for go-ipfs binaries

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/ceramic#180]
They have to be predictably available via URL

**Comment by ukstv** [comment]
@stbrody mind owning this maybe?

**Comment by stbrody** [comment]
@ukstv what does this mean?  dag-jose support is getting merged upstream, so we should be able to use the official binaries once it's released

**Comment by ukstv** [comment]
@stbrody ORLY? My understanding was that the binary we are going to use diverges from vanilla somehow (S3? metrics?).

If we are going with vanilla go-ipfs, things are much-much simpler.

**Comment by stbrody** [comment]
@smrz2001 can confirm, but I'm 90% sure it should be vanilla go-ipfs once the next release happens after dag-jose is merged.  Of course I have no idea how long it will be between merge and release...

**Comment by stbrody** [comment]
> Of course I have no idea how long it will be between merge and release

So we may still want some kind of workaround so we can start at least developing and testing with go-ipfs before the dagjose support is fully released, but it doesn't need to be production quality

**Comment by ukstv** [comment]
Any expectation about duration of this transitory period?

**Comment by smrz2001** [comment]
It can't be the vanilla `go-ipfs` for deployments (but probably can for tests).

For deployments, [here's](https://github.com/ceramicnetwork/go-ipfs-daemon) where our deployed Docker image (with its own compiled binary) will be coming from.

I don't think we'll be able to get away from distributing our own image/binary in the long run. 

FYI, for immediate testing, this line from the Dockerfile will need to point to my go-ipfs PR, which in turn currently points to my go-dag-jose PR. Once my go-ipfs PR is merged we can point to vanilla go-ipfs but to my commit hash. Once it is fully released, we can point to a proper release. All that to say, we aren't blocked. 

```
RUN​ git clone --depth 1 --branch v0.10.0 https://github.com/ipfs/go-ipfs
```

**Comment by ukstv** [comment]
Okay, let this wait till Mohsin and Val are back, to consider if this should be discarded. For tests this is clearly not needed, if vanilla go-ipfs is used.
