### ISSUE TITLE
Minor IDX.XYZ cleanups 

### ISSUE THREAD

**Issue by dazuck** [ceramicnetwork/ceramic#26]
A few tiny things I noticed going through the idx.xyz site

- [ ] copyright is "3Box Labs" on landing page and "Ceramic Studio" on docs. If we copyright at all it should be "3Box Inc" but we can also just say "made with ♥ by 3Box Labs" -- no real need for a copyright notice and if we have one it needs to be proper name 
- [ ] in the docs, seems like we could benefit from splitting out the first part of "Understanding Authentication" into its own header around reading identities - a lot of integrations will likely be read-only based on a DID or an address and making it obvious at the top level that's a supported use case might help conversion 
- [ ] I'd advocate for "Docs" rather than "Get Started" in nav bar to make it crystal clear. I actually thought it was missing a link to the docs at one point briefly. But i'm not a dev so maybe everyone else will get it :)

**Comment by PaulLeCam** [comment]
Thanks for the feedback, sorry I was hoping to make the changes along with the 0.2 release today but as it's been delayed I pushed them now. Please let me know @dazuck if it looks good to you or I should make further changes!
