### ISSUE TITLE
Repo for js-ipfs with dag-jose enabled

### ISSUE THREAD

**Issue by simonovic86** [ceramicnetwork/ceramic#35]
- create a repo which will contain all the necessary configuration for starting a standalone `js-ipfs` instance with `API`s enabled
- should enable `dag-jose` codec by default.

**Comment by oed** [comment]
Is the artifact of this repo a docker file?

**Comment by simonovic86** [comment]
@oed yes, the `Dockerfile` will be used in most of the cases but we should be able to run it as `npm start` as well. This repo will be used for deployment, Clayground and manual testing/debugging.
