### ISSUE TITLE
is document encryption & abstraction possible?

### ISSUE THREAD

**Issue by Kingz042** [ceramicnetwork/ceramic#44]
DIDs own documents that may only be created or edited by them but the open network allows for the query visibility of all created documents on the network is it possible to see proof of a document in query but restrict the visibility of the document content with only the DID providing permissions for this viewing ? this question is relevant in terms of determining if personal private data can be used on an enterprise blockchain running this network protocol as to increase transparency but also ensure security

**Comment by oed** [comment]
Encrypted content in ceramic documents is definitely possible. It's a planned feature in the protocol to have read keys for documents and the DID libraries that we use already support encryption. If you need encryption right now you can use the JWE functionality of the [`dids`](https://ceramicnetwork.github.io/js-did/classes/did.html) library which is used by js-ceramic.

**Comment by ShravanSunder** [comment]
@oed what is the current state of encryption of data?
