### ISSUE TITLE
BUG: 5XX Bad gateway error on ceramic requests

### ISSUE THREAD

**Issue by abhisingh3195** [ceramicnetwork/ceramic#53]
**Describe the bug**
 I sometimes get this error of 500 bad gateway while interacting through ceramic and it makes the user to refresh the application(retrying ceramic requests) and try again.

**To Reproduce**
1 - Using packages @ceramicnetwork/http-client, @ceramicstudio/idx, 3id-connect
2 - Sometimes, when i get the error,it's most of the time has these endpoints like - 
     a - https://ceramic-clay.3boxlabs.com/api/v0/documents
     b -  https://ceramic-clay.3boxlabs.com/api/v0/pins/
3 - There's a phase in my  app where i am in need to get all the user details and so it may happens during that. 
4 - Code where i think this error comes - 
      userDid ---> all user's DIDs 
      let promiseArray = [];
      for(let i in userDID.data){
        let DID = userDID.data[i].userDid;
        promiseArray.push(blockchainDetails.idx.get('basicProfile',DID))
      }
      let allUsers = yield Promise.all(promiseArray);

**Expected behavior**
It should work as the rest of times it does,giving me the user details.

**Screenshots**
![Screenshot from 2021-03-25 13-08-03](https://user-images.githubusercontent.com/62532644/113248381-7a75d300-92da-11eb-872c-65bcc840ccd3.png)
![Screenshot from 2021-03-25 13-07-34](https://user-images.githubusercontent.com/62532644/113248385-7ea1f080-92da-11eb-9aa7-4ae4c733f7ca.png)
![screenshot_from_2021-04-01_11-08-10__01](https://user-images.githubusercontent.com/62532644/113248619-f4a65780-92da-11eb-960d-a6f8ed19d432.png)

**Ceramic versions** 
"@ceramicnetwork/http-client": "^0.9.3",
"@ceramicstudio/idx": "^0.7.0",
"3id-connect": "^1.0.0-alpha.13",

**Machine, OS, browser information (please complete the following information):**
Linux,testing on Chrome and Brave only for right now.

**Additional context**
It comes sometimes so not able to exactly know why is it coming.

**Comment by oed** [comment]
@valmack mind having a look at this? ☝️

**Comment by ALuhning** [comment]
I am also experiencing these issues - pretty much identical to everything already mentioned.

Packages I'm using:
 "@ceramicnetwork/http-client": "^0.9.6",
 "@ceramicstudio/idx": "^0.8.0",
 "@ceramicstudio/idx-tools": "^0.8.0",

Same endpoints.  Usually occurs during a idx.get or idx.set.

Issue gets fixed with a page refresh, but occurs frequently - probably 50-75% of page loads.

**Comment by valmack** [comment]
@abhisingh3195 @ALuhning our clay nodes have just been updated. Can you try this again and let me know if you are still seeing the issues?

Otherwise if you can provide clear repro steps (including a complete code sample) I can try to debug from that.

**Comment by ALuhning** [comment]
Have been testing/running the app most of the afternoon without issue (no 500 errors at all) in places where I used to see issues.    Might be fixed - will continue to check it out, but wanted to provide some initial feedback.

**Comment by abhisingh3195** [comment]
@valmack Sorry for the late response, I will also test it and will let you know but I want to know that after updating your clay nodes,does it lead to clearing of previous stored data of users on ceramics because I am not able to see previous stored details of user now.

**Comment by valmack** [comment]
> @valmack I will also test it and will let you know but I want to know that after updating your clay nodes,does it lead to clearing of previous stored data of users on ceramics because I am not able to see previous stored details of user now.

yes this infrastructure update included critical changes that cleared some data on our nodes

Closing this as it seems to be resolved

**Comment by tahpot** [comment]
This appears to be happening again.

We are getting this on a regular basis (every few hours) on a server we are running.

**Comment by v-stickykeys** [comment]
@tahpot can you provide more details?

What requests are you making and what errors? Does it happen every time that request is made? Is it still happening today?
